- name: Test Connectivity to servers
  hosts: db-server, web-server-1, web-server-2
  vars:
    ansible_ssh_private_key_file: "SSH_private_key"
    ansible_user: "Google_username"

  tasks:
    - ping:

# ansible-playbook manage-instances.yml -i inventory